import React, { useMemo, useState } from "react";
import { Panel, Chip, Markdown, Loading } from "@/components/jscenter/JSUI";
import { BoardCard, ComponentCard, SnippetCard } from "@/components/jscenter/KnowledgeRef";
import {
  BOARDS, COMPONENTS, COMPONENT_CATEGORIES, SNIPPETS, SYLLABUS, FORMULAS, SAFETY_RULES, searchKnowledge,
} from "@/lib/jscenter/knowledge";
import { streamMentor } from "@/lib/jscenter/mentor";
import { useJSProfile } from "@/hooks/useJSProfile";
import { Library, Search, Sparkles, ShieldAlert, Sigma, Cpu, Code2, GraduationCap, Puzzle } from "lucide-react";

type Tab = "syllabus" | "parts" | "boards" | "snippets" | "formulas" | "safety";

const TABS: Array<{ key: Tab; label: string; icon: React.ReactNode }> = [
  { key: "syllabus", label: "Syllabus", icon: <GraduationCap className="h-3.5 w-3.5" /> },
  { key: "parts", label: "Components", icon: <Puzzle className="h-3.5 w-3.5" /> },
  { key: "boards", label: "Boards & Pinouts", icon: <Cpu className="h-3.5 w-3.5" /> },
  { key: "snippets", label: "Code Snippets", icon: <Code2 className="h-3.5 w-3.5" /> },
  { key: "formulas", label: "Formulas", icon: <Sigma className="h-3.5 w-3.5" /> },
  { key: "safety", label: "Safety & Honesty", icon: <ShieldAlert className="h-3.5 w-3.5" /> },
];

/** AI deep dive on any topic in the library. */
const DeepDive: React.FC<{ seed: string }> = ({ seed }) => {
  const { profile } = useJSProfile();
  const [topic, setTopic] = useState(seed);
  const [text, setText] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const go = async () => {
    if (!topic.trim()) return;
    setBusy(true); setError(null); setText("");
    try {
      await streamMentor("explain", { topic, classLevel: profile.class_level ?? undefined }, [], (c) => setText((t) => t + c));
    } catch (e) {
      setError(e instanceof Error ? e.message : "JARVIS could not generate this.");
    } finally { setBusy(false); }
  };

  return (
    <Panel title="Deep dive with JARVIS" icon={<Sparkles className="h-3.5 w-3.5 text-primary" />}>
      <div className="flex gap-2">
        <input value={topic} onChange={(e) => setTopic(e.target.value)} placeholder="Any topic, sensor, formula or error…"
          className="flex-1 bg-muted/40 rounded-md px-2 py-2 text-xs outline-none" />
        <button onClick={go} disabled={busy || !topic.trim()}
          className="rounded-md border border-primary/40 bg-primary/10 px-3 text-xs text-primary disabled:opacity-50">Explain</button>
      </div>
      {error && <p className="mt-2 text-sm text-destructive">{error}</p>}
      {busy && !text && <div className="mt-3"><Loading /></div>}
      {text && <div className="mt-2"><Markdown text={text} /></div>}
    </Panel>
  );
};

export default function JSLibrary() {
  const [tab, setTab] = useState<Tab>("syllabus");
  const [q, setQ] = useState("");
  const [cat, setCat] = useState<string>("All");
  const [subject, setSubject] = useState<string>("All");

  const hits = useMemo(() => searchKnowledge(q), [q]);
  const subjects = useMemo(() => ["All", ...Array.from(new Set(SYLLABUS.map((u) => u.subject)))], []);
  const units = SYLLABUS.filter((u) => subject === "All" || u.subject === subject);
  const parts = COMPONENTS.filter((c) => cat === "All" || c.category === cat);

  return (
    <div className="space-y-4">
      <Panel title="Knowledge Library" icon={<Library className="h-3.5 w-3.5 text-primary" />}>
        <div className="space-y-3">
          <p className="text-xs text-muted-foreground">
            Curated offline reference for every JS Center tool — syllabus topics, component wiring, board pinouts, snippets,
            formulas and safety rules. Anything deeper is generated by JARVIS on demand.
          </p>
          <div className="flex items-center gap-2 rounded-md bg-muted/40 px-2">
            <Search className="h-3.5 w-3.5 text-muted-foreground" />
            <input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Search everything: ESP32 ADC, pH, servo, accuracy…"
              className="flex-1 bg-transparent py-2 text-xs outline-none" />
          </div>
        </div>
      </Panel>

      {q.trim() && (
        <Panel title={`Search results (${hits.length})`} icon={<Search className="h-3.5 w-3.5 text-primary" />}>
          {hits.length === 0 ? (
            <p className="text-sm text-muted-foreground">No match in the offline library — use the deep dive below.</p>
          ) : (
            <ul className="space-y-2">
              {hits.map((h) => (
                <li key={h.kind + h.id} className="rounded-lg border border-primary/15 bg-background/40 p-2.5">
                  <div className="flex items-center gap-2">
                    <Chip tone="primary">{h.kind}</Chip>
                    <span className="text-sm text-foreground/90">{h.title}</span>
                  </div>
                  <p className="mt-1 text-xs text-muted-foreground">{h.detail}</p>
                </li>
              ))}
            </ul>
          )}
        </Panel>
      )}

      <div className="flex gap-2 overflow-x-auto pb-1">
        {TABS.map((t) => (
          <button key={t.key} onClick={() => setTab(t.key)}
            className={`flex items-center gap-1.5 whitespace-nowrap rounded-full border px-3 py-1.5 text-xs transition ${tab === t.key ? "border-primary/60 bg-primary/15 text-primary" : "border-border text-muted-foreground hover:text-primary"}`}>
            {t.icon} {t.label}
          </button>
        ))}
      </div>

      {tab === "syllabus" && (
        <Panel title="Syllabus map" icon={<GraduationCap className="h-3.5 w-3.5 text-primary" />}>
          <select value={subject} onChange={(e) => setSubject(e.target.value)} className="mb-3 w-full bg-muted/40 rounded-md px-2 py-2 text-xs">
            {subjects.map((s) => <option key={s} value={s}>{s}</option>)}
          </select>
          <div className="space-y-3">
            {units.map((u) => (
              <div key={u.subject + u.classes} className="rounded-xl border border-primary/20 bg-background/40 p-3">
                <div className="flex items-center gap-2">
                  <Chip tone="primary">{u.subject}</Chip>
                  <Chip>Class {u.classes}</Chip>
                </div>
                <ul className="mt-2 space-y-2">
                  {u.topics.map((t) => (
                    <li key={t.topic} className="border-t border-border/40 pt-2 first:border-0 first:pt-0">
                      <div className="text-sm font-medium text-foreground/90">{t.topic}</div>
                      <p className="text-xs text-muted-foreground">{t.core}</p>
                      <p className="mt-0.5 text-xs text-primary/80">Project idea: {t.projectHook}</p>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </Panel>
      )}

      {tab === "parts" && (
        <Panel title={`Components (${parts.length})`} icon={<Puzzle className="h-3.5 w-3.5 text-primary" />}>
          <div className="mb-3 flex flex-wrap gap-1.5">
            {["All", ...COMPONENT_CATEGORIES].map((c) => (
              <button key={c} onClick={() => setCat(c)}>
                <Chip tone={cat === c ? "primary" : "muted"}>{c}</Chip>
              </button>
            ))}
          </div>
          <div className="space-y-2">{parts.map((c) => <ComponentCard key={c.id} item={c} />)}</div>
        </Panel>
      )}

      {tab === "boards" && (
        <Panel title="Boards & pinouts" icon={<Cpu className="h-3.5 w-3.5 text-primary" />}>
          <div className="space-y-3">{BOARDS.map((b) => <BoardCard key={b.id} board={b} />)}</div>
        </Panel>
      )}

      {tab === "snippets" && (
        <Panel title="Snippet library" icon={<Code2 className="h-3.5 w-3.5 text-primary" />}>
          <div className="space-y-3">{SNIPPETS.map((s) => <SnippetCard key={s.id} item={s} />)}</div>
        </Panel>
      )}

      {tab === "formulas" && (
        <Panel title="Formula sheet" icon={<Sigma className="h-3.5 w-3.5 text-primary" />}>
          <div className="overflow-x-auto rounded-lg border border-primary/20">
            <table className="w-full text-xs">
              <thead className="bg-primary/10 text-primary">
                <tr><th className="px-2 py-1.5 text-left font-medium">Name</th><th className="px-2 py-1.5 text-left font-medium">Formula</th><th className="px-2 py-1.5 text-left font-medium">Use</th></tr>
              </thead>
              <tbody>
                {FORMULAS.map((f) => (
                  <tr key={f.name} className="border-t border-border/50">
                    <td className="px-2 py-1.5 align-top text-foreground/90">{f.name}</td>
                    <td className="px-2 py-1.5 align-top font-mono text-primary">{f.expr}</td>
                    <td className="px-2 py-1.5 align-top text-muted-foreground">{f.where}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Panel>
      )}

      {tab === "safety" && (
        <Panel title="Safety & honesty rules" icon={<ShieldAlert className="h-3.5 w-3.5 text-primary" />}>
          <div className="space-y-3">
            {SAFETY_RULES.map((g) => (
              <div key={g.title} className="rounded-xl border border-primary/20 bg-background/40 p-3">
                <h3 className="text-sm font-semibold text-primary">{g.title}</h3>
                <ul className="mt-1 space-y-1 pl-4">
                  {g.rules.map((r) => (
                    <li key={r} className="relative text-xs text-muted-foreground before:absolute before:-left-3 before:top-1.5 before:h-1 before:w-1 before:rounded-full before:bg-primary">{r}</li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </Panel>
      )}

      <DeepDive seed="" />
      <p className="pb-6 text-[11px] text-muted-foreground/70">
        Reference values are typical for common Indian-market modules — verify pins and thresholds on your own hardware.
      </p>
    </div>
  );
}
