/**
 * JS CENTER — shared offline knowledge base.
 * Hybrid model: this file holds curated, instant reference data.
 * Deep dives beyond this are generated by JARVIS (mentor `explain` mode) and cached.
 */

/* ------------------------------------------------------------------ boards */

export interface BoardRef {
  id: string;
  name: string;
  /** Platform ids from the Code Lab that map to this board. */
  platforms: string[];
  logic: string;
  input: string;
  digital: string;
  analog: string;
  pwm: string;
  special: string[];
  notes: string[];
}

export const BOARDS: BoardRef[] = [
  {
    id: "arduino-uno",
    name: "Arduino UNO / Nano (ATmega328P)",
    platforms: ["arduino-uno"],
    logic: "5 V logic, 40 mA max per pin (200 mA total)",
    input: "USB 5 V, or 7–12 V on VIN / barrel jack",
    digital: "D0–D13 (D0/D1 are Serial — avoid while uploading)",
    analog: "A0–A5, 10-bit ADC (0–1023)",
    pwm: "D3, D5, D6, D9, D10, D11 (~490 Hz; D5/D6 ~980 Hz)",
    special: ["I2C: A4 = SDA, A5 = SCL", "SPI: D11 MOSI, D12 MISO, D13 SCK, D10 SS", "Interrupts: D2, D3", "LED_BUILTIN = D13"],
    notes: [
      "Servos and motors must have their own supply — never power more than one small servo from the 5 V pin.",
      "Common ground between board and external supply is mandatory.",
    ],
  },
  {
    id: "arduino-mega",
    name: "Arduino Mega 2560",
    platforms: ["arduino-mega"],
    logic: "5 V logic",
    input: "USB 5 V, or 7–12 V VIN",
    digital: "D0–D53",
    analog: "A0–A15, 10-bit ADC",
    pwm: "D2–D13, D44–D46",
    special: ["I2C: D20 SDA, D21 SCL", "SPI: D50 MISO, D51 MOSI, D52 SCK, D53 SS", "4 hardware serial ports", "Interrupts: D2, D3, D18–D21"],
    notes: ["Choose Mega when you need many sensors, LCD + keypad + SD together, or several serial devices (GPS + GSM)."],
  },
  {
    id: "esp32",
    name: "ESP32 DevKit v1",
    platforms: ["esp32"],
    logic: "3.3 V logic — 5 V sensor outputs need a divider or level shifter",
    input: "USB 5 V (VIN 5 V), regulator gives 3.3 V",
    digital: "GPIO 0–39 (34–39 are input-only, no pull-ups)",
    analog: "ADC1: GPIO 32–39 (usable with WiFi). ADC2 pins fail while WiFi is on. 12-bit (0–4095)",
    pwm: "Any output GPIO via ledcWrite / 16 LEDC channels",
    special: ["Default I2C: GPIO21 SDA, GPIO22 SCL", "Default SPI: 18 SCK, 19 MISO, 23 MOSI, 5 CS", "Touch pins: GPIO 4, 12, 13, 14, 15, 27, 32, 33", "Built-in WiFi + Bluetooth"],
    notes: [
      "Avoid GPIO 6–11 (connected to flash) and strapping pins 0, 2, 12, 15 at boot.",
      "Hold BOOT while uploading if the IDE reports 'Failed to connect'.",
    ],
  },
  {
    id: "esp8266",
    name: "ESP8266 / NodeMCU",
    platforms: ["esp8266"],
    logic: "3.3 V logic",
    input: "USB 5 V / VIN",
    digital: "D0–D8 (GPIO16, 5, 4, 0, 2, 14, 12, 13, 15)",
    analog: "Single A0, 0–1.0 V at the chip (NodeMCU board divider makes it 0–3.3 V), 10-bit",
    pwm: "Software PWM on most GPIO, analogWrite range 0–1023",
    special: ["I2C: D1 SCL, D2 SDA (software I2C)", "Deep sleep needs D0–RST wire", "Built-in WiFi"],
    notes: ["D3/D4/D8 are boot-mode pins — keep them free at power-up.", "Only one analog input: use an ADS1115 for more."],
  },
  {
    id: "raspberry-pi",
    name: "Raspberry Pi (40-pin header)",
    platforms: ["raspberry-pi"],
    logic: "3.3 V logic — NEVER feed 5 V into a GPIO",
    input: "USB-C / micro-USB 5 V, 2.5–3 A",
    digital: "BCM GPIO 2–27 on the 40-pin header",
    analog: "No ADC on board — use MCP3008 (SPI) or ADS1115 (I2C)",
    pwm: "Hardware PWM: GPIO12, 13, 18, 19; software PWM elsewhere",
    special: ["I2C: GPIO2 SDA, GPIO3 SCL", "SPI: GPIO10 MOSI, 9 MISO, 11 SCLK, 8 CE0", "UART: GPIO14 TX, GPIO15 RX", "Camera via CSI ribbon"],
    notes: ["Enable I2C/SPI/Camera with `sudo raspi-config`.", "Always shut down with `sudo shutdown -h now` before pulling power."],
  },
  {
    id: "pico",
    name: "Raspberry Pi Pico (MicroPython)",
    platforms: ["micropython"],
    logic: "3.3 V logic",
    input: "USB 5 V on VSYS, or 1.8–5.5 V battery on VSYS",
    digital: "GP0–GP28",
    analog: "ADC: GP26, GP27, GP28 (12-bit) + internal temperature sensor",
    pwm: "PWM on every GP pin (16 slices)",
    special: ["I2C0: GP0 SDA, GP1 SCL", "SPI0: GP16 MISO, GP18 SCK, GP19 MOSI", "Onboard LED = GP25 ('LED' on Pico W)"],
    notes: ["Hold BOOTSEL while plugging in to flash firmware.", "Use Thonny for the fastest classroom workflow."],
  },
];

export function boardForPlatform(platformId: string): BoardRef | undefined {
  return BOARDS.find((b) => b.platforms.includes(platformId));
}

/* -------------------------------------------------------------- components */

export interface ComponentRef {
  id: string;
  name: string;
  category: "Sensor" | "Actuator" | "Display" | "Communication" | "Power" | "Module";
  purpose: string;
  voltage: string;
  interface: string;
  pins: string;
  library: string;
  priceINR: string;
  gotchas: string[];
  snippet?: string;
}

export const COMPONENTS: ComponentRef[] = [
  {
    id: "dht11",
    name: "DHT11 / DHT22 temperature + humidity",
    category: "Sensor",
    purpose: "Air temperature and relative humidity",
    voltage: "3.3–5 V",
    interface: "1-wire digital (custom protocol)",
    pins: "VCC, DATA → any digital pin (10 kΩ pull-up to VCC), GND",
    library: "Adafruit DHT sensor library + Adafruit Unified Sensor",
    priceINR: "₹80–₹250",
    gotchas: ["DHT11 reads only whole degrees; DHT22 is ±0.5 °C.", "Minimum 2 s between reads or you get NaN."],
    snippet: `#include "DHT.h"
DHT dht(2, DHT11);       // DATA on D2
void setup(){ Serial.begin(9600); dht.begin(); }
void loop(){
  float t = dht.readTemperature(), h = dht.readHumidity();
  if (isnan(t) || isnan(h)) { Serial.println("sensor read failed"); }
  else { Serial.print(t); Serial.print(" C  "); Serial.print(h); Serial.println(" %"); }
  delay(2000);
}`,
  },
  {
    id: "hcsr04",
    name: "HC-SR04 ultrasonic distance",
    category: "Sensor",
    purpose: "Distance 2–400 cm (level, obstacle, parking)",
    voltage: "5 V (use a divider on ECHO for 3.3 V boards)",
    interface: "TRIG pulse + ECHO pulse width",
    pins: "VCC, TRIG → digital out, ECHO → digital in, GND",
    library: "None needed (pulseIn) or NewPing",
    priceINR: "₹60–₹120",
    gotchas: ["Distance cm = pulse_µs / 58.", "Soft/angled surfaces absorb the echo — expect dropouts."],
    snippet: `const int TRIG = 9, ECHO = 10;
void setup(){ Serial.begin(9600); pinMode(TRIG, OUTPUT); pinMode(ECHO, INPUT); }
void loop(){
  digitalWrite(TRIG, LOW); delayMicroseconds(2);
  digitalWrite(TRIG, HIGH); delayMicroseconds(10); digitalWrite(TRIG, LOW);
  long us = pulseIn(ECHO, HIGH, 30000);
  Serial.println(us ? us / 58.0 : -1);   // -1 = out of range
  delay(200);
}`,
  },
  {
    id: "soil",
    name: "Capacitive soil-moisture sensor",
    category: "Sensor",
    purpose: "Soil water content for smart-irrigation projects",
    voltage: "3.3–5 V",
    interface: "Analog voltage",
    pins: "VCC, AOUT → analog pin, GND",
    library: "None",
    priceINR: "₹120–₹250",
    gotchas: [
      "Buy capacitive, not resistive — resistive probes corrode within days.",
      "Raw values are board-specific: calibrate dry-air and fully-wet readings and map() between them.",
    ],
  },
  {
    id: "mq135",
    name: "MQ-135 / MQ-2 gas sensor",
    category: "Sensor",
    purpose: "Air quality / smoke / LPG indication",
    voltage: "5 V (heater draws ~150 mA)",
    interface: "Analog + digital threshold",
    pins: "VCC, AOUT → analog pin, DOUT (optional), GND",
    library: "MQUnifiedsensor (optional)",
    priceINR: "₹150–₹300",
    gotchas: [
      "Needs 24–48 h burn-in and 2–3 min warm-up for stable readings.",
      "Uncalibrated MQ output is an INDICATION, not a ppm measurement — say so to judges.",
    ],
  },
  {
    id: "bmp280",
    name: "BMP280 / BME280 pressure sensor",
    category: "Sensor",
    purpose: "Barometric pressure, altitude, temperature (BME adds humidity)",
    voltage: "3.3 V (most breakouts accept 5 V)",
    interface: "I2C (0x76 or 0x77) or SPI",
    pins: "VCC, GND, SDA, SCL",
    library: "Adafruit BMP280 / BME280",
    priceINR: "₹150–₹400",
    gotchas: ["If begin() fails, try the other I2C address.", "Altitude needs the local sea-level pressure to be accurate."],
  },
  {
    id: "mpu6050",
    name: "MPU6050 accelerometer + gyroscope",
    category: "Sensor",
    purpose: "Tilt, vibration, earthquake alarm, self-balancing robots",
    voltage: "3.3–5 V (breakout has a regulator)",
    interface: "I2C (0x68)",
    pins: "VCC, GND, SDA, SCL, INT (optional)",
    library: "Adafruit MPU6050 or MPU6050_light",
    priceINR: "₹120–₹250",
    gotchas: ["Calibrate offsets while completely still at startup.", "Gyro drifts — fuse with the accelerometer (complementary filter)."],
  },
  {
    id: "ldr",
    name: "LDR (light-dependent resistor)",
    category: "Sensor",
    purpose: "Light level — street lights, solar trackers",
    voltage: "Any (needs a divider)",
    interface: "Analog voltage divider",
    pins: "LDR + 10 kΩ resistor in series, midpoint → analog pin",
    library: "None",
    priceINR: "₹5–₹20",
    gotchas: ["Response is non-linear; only use it for relative light, never lux without calibration."],
  },
  {
    id: "pir",
    name: "PIR motion sensor (HC-SR501)",
    category: "Sensor",
    purpose: "Human motion detection",
    voltage: "5 V",
    interface: "Digital HIGH pulse",
    pins: "VCC, OUT → digital in, GND (two trimmers: sensitivity, delay)",
    library: "None",
    priceINR: "₹70–₹150",
    gotchas: ["Needs 30–60 s to stabilise after power-up.", "Detects heat movement — a still person can be missed."],
  },
  {
    id: "servo",
    name: "SG90 / MG996R servo motor",
    category: "Actuator",
    purpose: "Angular motion — gates, arms, solar trackers",
    voltage: "4.8–6 V (MG996R needs 1–2 A peaks)",
    interface: "50 Hz PWM signal",
    pins: "Orange signal → PWM pin, red 5 V (external), brown GND (shared)",
    library: "Servo.h (Arduino) / ESP32Servo",
    priceINR: "₹90–₹450",
    gotchas: ["Never power a servo from the board's 5 V rail on a real model — brown-out resets follow.", "Grounds must be common."],
    snippet: `#include <Servo.h>
Servo s;
void setup(){ s.attach(9); }
void loop(){ s.write(0); delay(800); s.write(90); delay(800); }`,
  },
  {
    id: "relay",
    name: "5 V relay module (1/2/4 channel)",
    category: "Actuator",
    purpose: "Switching pumps, lamps, fans",
    voltage: "5 V coil, contacts up to 250 VAC / 10 A",
    interface: "Active-LOW digital input on most modules",
    pins: "VCC, GND, IN → digital pin; load on COM + NO",
    library: "None",
    priceINR: "₹70–₹300",
    gotchas: [
      "Most cheap modules are ACTIVE LOW — digitalWrite(pin, LOW) turns them ON.",
      "Mains wiring is for adults only. For school exhibitions switch a 12 V or battery load, never 230 V.",
    ],
  },
  {
    id: "l298n",
    name: "L298N / L293D motor driver",
    category: "Actuator",
    purpose: "Driving DC motors and small robot wheels both directions",
    voltage: "Motor 5–35 V, logic 5 V",
    interface: "2 direction pins + 1 enable (PWM) per motor",
    pins: "IN1/IN2 → digital, ENA → PWM, OUT1/OUT2 → motor",
    library: "None",
    priceINR: "₹120–₹250",
    gotchas: ["L298N drops ~2 V — use a 9 V pack for 6 V motors.", "Remove the 5 V jumper when the motor supply is above 12 V."],
  },
  {
    id: "pump",
    name: "Mini submersible water pump (3–6 V)",
    category: "Actuator",
    purpose: "Irrigation and water-treatment models",
    voltage: "3–6 V DC, 100–200 mA",
    interface: "Switched through a relay or MOSFET",
    pins: "Pump + → supply, pump − → MOSFET drain / relay contact",
    library: "None",
    priceINR: "₹100–₹200",
    gotchas: ["Must stay submerged or it burns out.", "Add a flyback diode when switching with a transistor."],
  },
  {
    id: "oled",
    name: "0.96\" OLED (SSD1306)",
    category: "Display",
    purpose: "Compact live readings on the model",
    voltage: "3.3–5 V",
    interface: "I2C (0x3C typical)",
    pins: "VCC, GND, SDA, SCL",
    library: "Adafruit SSD1306 + Adafruit GFX",
    priceINR: "₹180–₹350",
    gotchas: ["Blank screen usually means the wrong I2C address — run an I2C scanner."],
  },
  {
    id: "lcd16x2",
    name: "16×2 LCD with I2C backpack",
    category: "Display",
    purpose: "Cheap readable text display for exhibitions",
    voltage: "5 V",
    interface: "I2C (0x27 or 0x3F)",
    pins: "VCC, GND, SDA, SCL",
    library: "LiquidCrystal_I2C",
    priceINR: "₹150–₹300",
    gotchas: ["If it shows only boxes, turn the contrast trimmer on the backpack."],
  },
  {
    id: "esp-wifi",
    name: "WiFi cloud upload (Blynk / ThingSpeak)",
    category: "Communication",
    purpose: "Live mobile dashboard for the judges",
    voltage: "—",
    interface: "HTTP / MQTT over the ESP WiFi stack",
    pins: "—",
    library: "WiFi.h + HTTPClient (ESP32), Blynk, ThingSpeak",
    priceINR: "Free tiers",
    gotchas: [
      "School WiFi often blocks devices — carry a phone hotspot as backup.",
      "ThingSpeak free tier accepts one update every 15 s.",
    ],
  },
  {
    id: "sd",
    name: "MicroSD card module",
    category: "Module",
    purpose: "Offline data logging for the Data Lab / graphs",
    voltage: "5 V module, 3.3 V logic inside",
    interface: "SPI",
    pins: "CS, MOSI, MISO, SCK + VCC, GND",
    library: "SD.h",
    priceINR: "₹90–₹200",
    gotchas: ["Format the card FAT32.", "Close the file after each write or you lose data on power cut."],
  },
  {
    id: "rtc",
    name: "DS3231 real-time clock",
    category: "Module",
    purpose: "Timestamps for logged data",
    voltage: "3.3–5 V",
    interface: "I2C (0x68)",
    pins: "VCC, GND, SDA, SCL",
    library: "RTClib",
    priceINR: "₹90–₹180",
    gotchas: ["Set the time once with the compile-time constructor, then re-upload without it."],
  },
  {
    id: "solar",
    name: "Solar panel + TP4056 charger",
    category: "Power",
    purpose: "Self-powered outdoor models",
    voltage: "6 V panel → TP4056 → 3.7 V Li-ion",
    interface: "—",
    pins: "Panel → IN+/IN−, cell → B+/B−, load → OUT+/OUT−",
    library: "—",
    priceINR: "₹150–₹500",
    gotchas: ["Use a protected TP4056 board.", "Never leave Li-ion cells charging unattended at school."],
  },
];

export const COMPONENT_CATEGORIES = ["Sensor", "Actuator", "Display", "Communication", "Module", "Power"] as const;

/* ---------------------------------------------------------------- snippets */

export interface SnippetRef {
  id: string;
  title: string;
  platform: string;
  language: string;
  what: string;
  code: string;
}

export const SNIPPETS: SnippetRef[] = [
  {
    id: "i2c-scan",
    title: "I2C scanner (find any module's address)",
    platform: "arduino-uno",
    language: "cpp",
    what: "First thing to run when an OLED / LCD / sensor 'does not work'.",
    code: `#include <Wire.h>
void setup(){
  Wire.begin(); Serial.begin(9600);
  for (byte a = 1; a < 127; a++) {
    Wire.beginTransmission(a);
    if (Wire.endTransmission() == 0) { Serial.print("Found 0x"); Serial.println(a, HEX); }
  }
}
void loop(){}`,
  },
  {
    id: "nonblocking",
    title: "Non-blocking timing (millis instead of delay)",
    platform: "arduino-uno",
    language: "cpp",
    what: "Lets sensors, display and alarm run together without freezing.",
    code: `unsigned long last = 0;
const unsigned long PERIOD = 1000;
void loop(){
  if (millis() - last >= PERIOD) { last = millis(); /* read sensor here */ }
  /* buzzer / button code keeps running every loop */
}`,
  },
  {
    id: "calibrate",
    title: "Calibrate an analog sensor into 0–100 %",
    platform: "arduino-uno",
    language: "cpp",
    what: "Turn raw ADC counts into a number a judge understands.",
    code: `const int DRY = 620, WET = 260;      // measure YOUR sensor and replace
int pct(int raw){ return constrain(map(raw, DRY, WET, 0, 100), 0, 100); }`,
  },
  {
    id: "esp-post",
    title: "ESP32 → ThingSpeak upload",
    platform: "esp32",
    language: "cpp",
    what: "Push one reading to a free cloud dashboard.",
    code: `#include <WiFi.h>
#include <HTTPClient.h>
void upload(float value){
  if (WiFi.status() != WL_CONNECTED) return;
  HTTPClient http;
  http.begin(String("http://api.thingspeak.com/update?api_key=YOUR_KEY&field1=") + value);
  http.GET();
  http.end();
}`,
  },
  {
    id: "pi-gpio",
    title: "Raspberry Pi GPIO input + output",
    platform: "raspberry-pi",
    language: "python",
    what: "Read a button, drive an LED.",
    code: `from gpiozero import LED, Button
from signal import pause
led, btn = LED(17), Button(27)
btn.when_pressed = led.on
btn.when_released = led.off
pause()`,
  },
  {
    id: "csv-log",
    title: "Log readings to CSV (laptop)",
    platform: "python",
    language: "python",
    what: "Capture serial data for graphs in the Data Lab.",
    code: `import csv, time, serial
ser = serial.Serial("COM3", 9600, timeout=2)   # /dev/ttyUSB0 on Linux
with open("data.csv", "w", newline="") as f:
    w = csv.writer(f); w.writerow(["t_s", "value"])
    t0 = time.time()
    while time.time() - t0 < 300:
        line = ser.readline().decode(errors="ignore").strip()
        if line:
            w.writerow([round(time.time() - t0, 2), line]); f.flush()`,
  },
  {
    id: "sklearn",
    title: "Train + evaluate a small ML model honestly",
    platform: "ml-python",
    language: "python",
    what: "Real machine learning — with a train/test split, so accuracy means something.",
    code: `import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

df = pd.read_csv("data.csv")
X, y = df.drop(columns=["label"]), df["label"]
Xtr, Xte, ytr, yte = train_test_split(X, y, test_size=0.25, random_state=42, stratify=y)
model = RandomForestClassifier(n_estimators=200, random_state=42).fit(Xtr, ytr)
print(classification_report(yte, model.predict(Xte)))   # report THIS, not training accuracy`,
  },
  {
    id: "opencv",
    title: "OpenCV live camera + colour mask",
    platform: "opencv",
    language: "python",
    what: "Base for object counting, waste sorting, plant-health demos.",
    code: `import cv2, numpy as np
cap = cv2.VideoCapture(0)
while True:
    ok, frame = cap.read()
    if not ok: break
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    mask = cv2.inRange(hsv, np.array([35, 80, 60]), np.array([85, 255, 255]))  # green
    cv2.imshow("mask", mask)
    if cv2.waitKey(1) == 27: break
cap.release(); cv2.destroyAllWindows()`,
  },
  {
    id: "pico-mp",
    title: "MicroPython sensor loop (Pico / ESP)",
    platform: "micropython",
    language: "python",
    what: "Minimal ADC read with the onboard LED as status.",
    code: `from machine import ADC, Pin
import time
adc, led = ADC(26), Pin(25, Pin.OUT)
while True:
    v = adc.read_u16() * 3.3 / 65535
    led.value(v > 1.6)
    print("{:.3f} V".format(v))
    time.sleep(1)`,
  },
  {
    id: "web-dash",
    title: "Web dashboard fetch + chart-free display",
    platform: "web",
    language: "javascript",
    what: "Show live values from an ESP endpoint on a phone browser.",
    code: `async function tick() {
  try {
    const r = await fetch("http://192.168.4.1/reading");
    document.getElementById("v").textContent = (await r.json()).value;
  } catch (e) { document.getElementById("v").textContent = "offline"; }
}
setInterval(tick, 2000); tick();`,
  },
];

/* ---------------------------------------------------------------- syllabus */

export interface TopicRef {
  topic: string;
  core: string;
  projectHook: string;
}

export interface SyllabusUnit {
  classes: string;
  subject: "Physics" | "Chemistry" | "Biology" | "Mathematics" | "Computer Science" | "Environmental Science";
  topics: TopicRef[];
}

export const SYLLABUS: SyllabusUnit[] = [
  {
    classes: "6–8",
    subject: "Physics",
    topics: [
      { topic: "Light, shadows and reflection", core: "Rectilinear propagation, plane-mirror images, pinhole camera.", projectHook: "Periscope, solar cooker, light-tracking blinds." },
      { topic: "Electricity and circuits", core: "Cells, series/parallel, conductors and insulators, switches.", projectHook: "Automatic night lamp with an LDR." },
      { topic: "Magnets and electromagnets", core: "Poles, magnetic field, current-carrying coil.", projectHook: "Electromagnetic crane, simple motor." },
      { topic: "Motion and measurement", core: "Speed = distance/time, SI units, measuring instruments.", projectHook: "Ultrasonic speed trap for toy cars." },
      { topic: "Heat transfer", core: "Conduction, convection, radiation; thermometers.", projectHook: "Insulation comparison box with data logging." },
    ],
  },
  {
    classes: "9–10",
    subject: "Physics",
    topics: [
      { topic: "Laws of motion & momentum", core: "F = ma, action–reaction, conservation of momentum.", projectHook: "Egg-drop crash-safety model with accelerometer." },
      { topic: "Work, energy, power", core: "W = F·s, KE = ½mv², PE = mgh, efficiency.", projectHook: "Speed-breaker or footstep power generator (report real efficiency)." },
      { topic: "Sound", core: "Frequency, wavelength, reflection, echo, SONAR.", projectHook: "Ultrasonic blind-stick / distance alarm." },
      { topic: "Electricity", core: "Ohm's law V = IR, resistance, heating effect, power P = VI.", projectHook: "Smart energy monitor with a current sensor." },
      { topic: "Magnetic effects of current", core: "Right-hand rule, solenoids, motors, induction.", projectHook: "Mini wind turbine with a DC generator." },
      { topic: "Light — reflection & refraction", core: "Mirror and lens formula, refractive index, power of lens.", projectHook: "Solar concentrator or automatic headlight dimmer." },
    ],
  },
  {
    classes: "11–12",
    subject: "Physics",
    topics: [
      { topic: "Electrostatics & capacitance", core: "Coulomb's law, field, potential, capacitor energy.", projectHook: "Capacitive water-level or soil sensor." },
      { topic: "Current electricity", core: "Kirchhoff's laws, Wheatstone bridge, potentiometer.", projectHook: "Precision strain/load cell bridge." },
      { topic: "Electromagnetic induction & AC", core: "Faraday, Lenz, transformers, RMS values.", projectHook: "Vibration energy harvester." },
      { topic: "Semiconductors", core: "Diodes, rectifiers, transistors, logic gates.", projectHook: "Solar charge controller." },
      { topic: "Optics & modern physics", core: "Interference, photoelectric effect, dual nature.", projectHook: "Photodiode-based air-quality turbidity meter." },
    ],
  },
  {
    classes: "9–12",
    subject: "Chemistry",
    topics: [
      { topic: "Acids, bases and salts", core: "pH scale, indicators, neutralisation.", projectHook: "Natural indicator paper + pH sensor water testing." },
      { topic: "Electrochemistry", core: "Electrolysis, galvanic cells, electrode potential.", projectHook: "Saltwater / lemon battery efficiency study." },
      { topic: "Chemical kinetics", core: "Rate laws, catalysts, temperature effect.", projectHook: "Catalyst comparison with timed reactions." },
      { topic: "Water & environmental chemistry", core: "Hardness, TDS, dissolved oxygen, pollutants.", projectHook: "Low-cost water purifier with before/after TDS data." },
      { topic: "Polymers & biodegradation", core: "Condensation vs addition polymers, degradation rates.", projectHook: "Bioplastic from starch, mass-loss study over 30 days." },
    ],
  },
  {
    classes: "9–12",
    subject: "Biology",
    topics: [
      { topic: "Photosynthesis & plant physiology", core: "Light reactions, stomata, transpiration.", projectHook: "Grow-light spectrum experiment with logged growth data." },
      { topic: "Human physiology", core: "Circulation, respiration, nervous coordination.", projectHook: "Pulse-oximeter style heart-rate monitor (educational, not medical)." },
      { topic: "Microbiology & hygiene", core: "Bacteria, sterilisation, antibiotics.", projectHook: "UV-C vs soap surface-cleaning comparison (adult supervision)." },
      { topic: "Ecology & biodiversity", core: "Food chains, ecosystems, pollution indicators.", projectHook: "Lichen / insect biodiversity index of your area." },
      { topic: "Genetics basics", core: "Mendelian inheritance, DNA structure.", projectHook: "Strawberry DNA extraction + inheritance survey." },
    ],
  },
  {
    classes: "9–12",
    subject: "Mathematics",
    topics: [
      { topic: "Statistics", core: "Mean, median, SD, correlation, sampling.", projectHook: "Every project needs 3+ trials, mean and error bars." },
      { topic: "Probability", core: "Events, distributions, expected value.", projectHook: "Traffic-flow or queueing simulation." },
      { topic: "Graphs & functions", core: "Linear regression, exponential and log fits.", projectHook: "Fit sensor calibration curves instead of guessing." },
      { topic: "Trigonometry & mensuration", core: "Angles, heights, volumes, surface area.", projectHook: "Solar-tracker angle calculation." },
    ],
  },
  {
    classes: "6–12",
    subject: "Computer Science",
    topics: [
      { topic: "Algorithmic thinking", core: "Sequence, selection, iteration, flowcharts.", projectHook: "Draw the flowchart before writing the sketch — judges ask for it." },
      { topic: "Embedded programming", core: "setup/loop, GPIO, ADC, PWM, interrupts, serial.", projectHook: "Every Arduino/ESP project in the Code Lab." },
      { topic: "Data handling", core: "CSV, pandas, plotting, cleaning outliers.", projectHook: "Data Lab graphs for your report." },
      { topic: "Machine learning basics", core: "Features, labels, train/test split, accuracy vs overfitting.", projectHook: "Only call it AI if you actually trained a model." },
      { topic: "IoT & networking", core: "WiFi, HTTP, MQTT, dashboards, latency.", projectHook: "Cloud dashboard for live judge demos." },
    ],
  },
  {
    classes: "6–12",
    subject: "Environmental Science",
    topics: [
      { topic: "Air quality", core: "PM2.5, AQI bands, sources of pollution.", projectHook: "AQI station — state clearly whether the sensor is calibrated." },
      { topic: "Water conservation", core: "Rainwater harvesting, greywater reuse, runoff.", projectHook: "Automated rainwater harvesting model." },
      { topic: "Waste management", core: "Segregation, composting, recycling streams.", projectHook: "Vision-based waste sorter." },
      { topic: "Renewable energy", core: "Solar, wind, biomass, capacity factor.", projectHook: "Compare panel angles with logged output." },
      { topic: "Climate & disasters", core: "Greenhouse effect, early-warning systems.", projectHook: "Flood or landslide early-warning prototype." },
    ],
  },
];

/* ---------------------------------------------------------------- formulas */

export interface FormulaRef { name: string; expr: string; where: string; subject: string }

export const FORMULAS: FormulaRef[] = [
  { name: "Ohm's law", expr: "V = I × R", where: "V volts, I amperes, R ohms", subject: "Physics" },
  { name: "Electrical power", expr: "P = V × I = I²R", where: "P watts", subject: "Physics" },
  { name: "Energy used", expr: "E (kWh) = P (W) × t (h) / 1000", where: "Billing / energy-saving projects", subject: "Physics" },
  { name: "Kinetic energy", expr: "KE = ½ m v²", where: "m kg, v m/s", subject: "Physics" },
  { name: "Potential energy", expr: "PE = m g h", where: "g = 9.81 m/s²", subject: "Physics" },
  { name: "Efficiency", expr: "η = (useful output / total input) × 100 %", where: "Always report this, never 'free energy'", subject: "Physics" },
  { name: "Speed of sound distance", expr: "d = (v × t) / 2", where: "v ≈ 343 m/s in air at 20 °C", subject: "Physics" },
  { name: "Ultrasonic distance (Arduino)", expr: "cm = pulse_µs / 58", where: "HC-SR04", subject: "Electronics" },
  { name: "Voltage divider", expr: "Vout = Vin × R2 / (R1 + R2)", where: "5 V → 3.3 V: R1 = 1 kΩ, R2 = 2 kΩ", subject: "Electronics" },
  { name: "LED series resistor", expr: "R = (Vsupply − Vled) / Iled", where: "Vled ≈ 2 V, Iled ≈ 15 mA", subject: "Electronics" },
  { name: "ADC to voltage", expr: "V = raw × Vref / (2^bits − 1)", where: "UNO: /1023 · ESP32: /4095", subject: "Electronics" },
  { name: "Solar panel output", expr: "P = V × I × fill factor", where: "Measure with a load, not open-circuit", subject: "Physics" },
  { name: "Percentage error", expr: "% error = |measured − true| / true × 100", where: "Required in every result table", subject: "Mathematics" },
  { name: "Mean & standard deviation", expr: "x̄ = Σx/n ; s = √(Σ(x − x̄)²/(n − 1))", where: "Minimum 3 trials", subject: "Mathematics" },
  { name: "Model accuracy", expr: "accuracy = correct predictions / total test samples", where: "Report on TEST data only", subject: "Computer Science" },
  { name: "pH", expr: "pH = −log₁₀[H⁺]", where: "0–14 scale", subject: "Chemistry" },
  { name: "Molarity", expr: "M = moles of solute / litres of solution", where: "Solution preparation", subject: "Chemistry" },
  { name: "Rate of reaction", expr: "rate = Δ[concentration] / Δtime", where: "Kinetics experiments", subject: "Chemistry" },
  { name: "Growth rate", expr: "GR = (final − initial) / days", where: "Plant / microbial studies", subject: "Biology" },
];

/* ------------------------------------------------------------------ safety */

export const SAFETY_RULES: Array<{ title: string; rules: string[] }> = [
  {
    title: "Electrical",
    rules: [
      "No 230 V mains wiring in a student model — switch a 5–12 V load instead.",
      "Always share a common ground between the board and any external supply.",
      "Check polarity twice before powering; reverse polarity kills modules instantly.",
      "Never draw motors or servos from the microcontroller's regulator.",
    ],
  },
  {
    title: "Chemical",
    rules: [
      "Goggles and gloves for every acid, base or heated reaction.",
      "No concentrated acids, chlorine gas generation, or unknown mixtures at school level.",
      "Dispose of chemical waste as your school lab instructs — never down the sink by default.",
    ],
  },
  {
    title: "Biological",
    rules: [
      "No human blood, saliva or pathogen culturing in a school project.",
      "Bacterial plates stay sealed; dispose by autoclave or the school protocol.",
      "Any human-subject survey needs consent and anonymised data.",
    ],
  },
  {
    title: "Battery & heat",
    rules: [
      "Never charge Li-ion cells unattended or overnight.",
      "Use a protection board (TP4056 with protection) for every Li-ion pack.",
      "Soldering: ventilated area, stand for the iron, adult supervision under class 9.",
    ],
  },
  {
    title: "Honesty rules (judges check these)",
    rules: [
      "Say 'expected result' until you have measured it yourself.",
      "Threshold if-else logic is automation, not machine learning — never claim AI without a trained model.",
      "Uncalibrated gas/turbidity sensors give indications, not ppm or NTU values.",
      "Cite every source and state clearly which parts you built vs bought.",
    ],
  },
];

/* ------------------------------------------------------------------ search */

export interface KnowledgeHit { kind: "Board" | "Component" | "Snippet" | "Topic" | "Formula" | "Safety"; title: string; detail: string; id: string }

export function searchKnowledge(q: string): KnowledgeHit[] {
  const s = q.trim().toLowerCase();
  if (!s) return [];
  const hits: KnowledgeHit[] = [];
  const has = (...parts: Array<string | undefined>) => parts.filter(Boolean).join(" ").toLowerCase().includes(s);

  BOARDS.forEach((b) => has(b.name, b.special.join(" "), b.analog, b.digital) &&
    hits.push({ kind: "Board", id: b.id, title: b.name, detail: `${b.logic} · ${b.analog}` }));
  COMPONENTS.forEach((c) => has(c.name, c.purpose, c.library, c.interface) &&
    hits.push({ kind: "Component", id: c.id, title: c.name, detail: c.purpose }));
  SNIPPETS.forEach((c) => has(c.title, c.what, c.platform) &&
    hits.push({ kind: "Snippet", id: c.id, title: c.title, detail: c.what }));
  SYLLABUS.forEach((u) => u.topics.forEach((t) => has(t.topic, t.core, t.projectHook, u.subject) &&
    hits.push({ kind: "Topic", id: `${u.subject}-${t.topic}`, title: `${t.topic} — ${u.subject} (${u.classes})`, detail: t.core })));
  FORMULAS.forEach((f) => has(f.name, f.expr, f.where, f.subject) &&
    hits.push({ kind: "Formula", id: f.name, title: `${f.name}: ${f.expr}`, detail: f.where }));
  SAFETY_RULES.forEach((g) => g.rules.forEach((r, i) => has(r, g.title) &&
    hits.push({ kind: "Safety", id: `${g.title}-${i}`, title: g.title, detail: r })));

  return hits.slice(0, 40);
}

/** Components most relevant to a Code Lab platform — used for the inline reference. */
export function componentsForPlatform(platformId: string): ComponentRef[] {
  if (platformId === "opencv" || platformId === "ml-python" || platformId === "python" || platformId === "web") {
    return COMPONENTS.filter((c) => ["sd", "esp-wifi"].includes(c.id));
  }
  return COMPONENTS.filter((c) => c.category !== "Power");
}

export function snippetsForPlatform(platformId: string): SnippetRef[] {
  const family: Record<string, string[]> = {
    "arduino-uno": ["arduino-uno"],
    "arduino-mega": ["arduino-uno"],
    esp32: ["esp32", "arduino-uno"],
    esp8266: ["esp32", "arduino-uno"],
    "raspberry-pi": ["raspberry-pi", "python"],
    micropython: ["micropython"],
    python: ["python"],
    "ml-python": ["ml-python", "python"],
    opencv: ["opencv", "python"],
    web: ["web"],
  };
  const keys = family[platformId] ?? [];
  return SNIPPETS.filter((s) => keys.includes(s.platform));
}
